import { StyleSheet } from 'react-native'

export default StyleSheet.create({
    full_width: {
        width: "100%",
        flex: 1,
        backgroundColor: '#000',
        justifyContent: 'flex-start',
        paddingTop: 50,
        paddingLeft: 10,
        paddingRight: 10,
    },
    container: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        width: "100%",
    },
    heading: {
        color: '#fff',
        fontSize: 28,
        fontWeight: 'bold',
        marginBottom: 20,
    },
    error: {
        color: 'red',
    },
    brand_text: {
        color: '#a3ff65',
    },
    divider: {
        marginTop: 10,
        marginBottom: 10,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        width: '100%',

    },
    divider_text: {
        color: '#6f6f6f',
        fontSize: 12,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    divider_bar: {
        width: "43%",
        overflow: 'hidden',
        height: 0.5,
        backgroundColor: '#6f6f6f',
        marginHorizontal: 10,
    },
    backButton: {
        marginBottom: 15,
    },
    image: {
        flex: 1,
        justifyContent: "center",
        width: "120%",
        resizeMode: "contain",
    },
    largeImageContainer: {
        height: "100%",
        width: "100%",
        resizeMode: "cover",
        display: "flex",
        flexDirection: "column-reverse",
    },
    viewContainer: {
        backgroundColor: "#000",
        borderTopRightRadius: 50,
        borderTopLeftRadius: 50,
        height: "45%",
        color: "#fff",
        paddingHorizontal: 30,
        paddingVertical: 10,
    },
    headingText: {
        fontSize: 40,
        fontWeight: "bold",
        textAlign: "center",
        marginTop: "10%",
        marginBottom: "5%",
        color: "#fff",
    },
    view: {
        marginVertical: 15,
    },
    input: {
        height: 60,
        width: '100%',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#6f6f6f',
        padding: 10,
        paddingLeft: 20,
        backgroundColor: 'transparent',
        color: '#fff',
        position: 'relative',
        textTransform: 'lowercase',

    },
    label: {
        color: '#6f6f6f',
        fontSize: 14,
        fontWeight: 'bold',
        marginBottom: 5,
    },
    icon: {
        position: 'absolute',
        right: 20,
        top: 42,
    },
    primary_button: {
        marginVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        paddingHorizontal: 32,
        borderRadius: 10,
        elevation: 3,
        backgroundColor: '#a3ff65',
    },
    secondary_button: {
        marginVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 15,
        paddingHorizontal: 32,
        borderRadius: 10,
        elevation: 3,
        backgroundColor: '#ffffff',
    },
    text: {
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: '#000',
    },
    light_text: {
        fontSize: 16,
        lineHeight: 21,
        fontWeight: 'bold',
        letterSpacing: 0.25,
        color: '#fff',
    },
    oauthButton: {
        paddingVertical: 15,
        marginVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#6f6f6f',
        position: 'relative',
    },
    oauthText: {
        fontSize: 16,
        lineHeight: 21,
        letterSpacing: 0.25,
        color: '#6f6f6f',
    },
    btn_icon: {
        position: 'absolute',
        left: 20,
        top: "65%",
    },
});
